# Generated by Django 3.0.2 on 2020-01-07 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('nutriscore', models.CharField(max_length=255)),
                ('fat', models.IntegerField()),
                ('saturated_fat', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('salt', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.CategoryDb')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_original', to='products.ProductDb')),
                ('product_replaceable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_replaceable', to='products.ProductDb')),
                ('user', models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
