# Generated by Django 3.0.2 on 2020-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200205_0844'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userpersonaldb',
            constraint=models.UniqueConstraint(fields=('original_product', 'replaced_product'), name='no_double'),
        ),
    ]
