# Generated by Django 3.0.2 on 2020-02-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200221_1442'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userpersonaldb',
            name='no_double',
        ),
    ]
