# Generated by Django 3.0.2 on 2020-02-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200222_1537'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userpersonaldb',
            constraint=models.UniqueConstraint(fields=('original_product', 'replaced_product', 'user'), name='no_double'),
        ),
    ]
