# Generated by Django 3.0.4 on 2020-03-29 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_auto_20200222_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpersonaldb',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='userpersonaldb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
